title: Moustapha Cheikh
description: "My personal website where you can find my blogs"

url: http://moustaphacheikh.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: moustaphacheikh
   twitter: mscheikh
   facebook: 
   email: moustapha.ml.cheikh@gmail.com

google_analytics: 
